### ISSUE TITLE
getting remote ollama to work

### ISSUE THREAD

**Issue by bozo32** [Nagi-ovo/CRAG-Ollama-Chat#3]
I have ollama running on another machine that I access through cloudflared. I get the 'ollama is running' confirmation when I access it directly, I can access/control that remote instance of ollama using open-webui but I can't seem to get the crag-ollama-chat config.yaml to connect to it.
I've tried /v1, :port/v1/the rest of it
any ideas?

Traceback (most recent call last):
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
    exec(code, module.__dict__)
  File "/Users/peter/ai-computing-assistant/CRAG-Ollama-Chat/app.py", line 66, in <module>
    vectorstore = Chroma.from_documents(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 778, in from_documents
    return cls.from_texts(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 736, in from_texts
    chroma_collection.add_texts(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 517, in embed_documents
    return self._get_len_safe_embeddings(texts, engine=engine)
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/langchain_openai/embeddings/base.py", line 333, in _get_len_safe_embeddings
    response = self.client.create(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/resources/embeddings.py", line 113, in create
    return self._post(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 902, in request
    return self._request(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 940, in _request
    return self._retry_request(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 1026, in _retry_request
    return self._request(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 940, in _request
    return self._retry_request(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 1026, in _retry_request
    return self._request(
  File "/Users/peter/miniconda3/envs/ollama-crag/lib/python3.10/site-packages/openai/_base_client.py", line 950, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.

**Comment by Nagi-ovo** [comment]
You can first try using your remote ollama on  your PC, and if it works, then test this project.
